services:
  medical-ai-assistant:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "7860:7860"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./lib/medchatinput/data:/app/lib/medchatinput/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
